import { ApolloClient, gql, InMemoryCache } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [data, setData] = useState(Array);
  const [flag, setFlag] = useState(false);

  useEffect(() => {
    fetch("http://localhost:3000/api/hello")
      .then((response) => response.json())
      .then((data) => setData(data.data.edges))
      .then(() => setFlag(true));
  }, []);

  function Redirect(url: string) {
    window.location.href = url;
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {data.map((value: any, id: number) => {
          console.log(value);
          return (
            <div
              className="py-6 flex flex-col justify-center relative overflow-hidden sm:py-8"
              // onClick={() => Redirect(value.node.url)}
            >
              <div className="absolute bg-center [mask-image:linear-gradient(180deg,white,rgba(255,255,255,0))]"></div>
              <div className="group hover:bg-sky-100 cursor-pointer relative px-6 pt-10 pb-8 bg-white shadow-xl ring-1 ring-gray-900/5 mx-5 sm:rounded-lg ">
                <div className=" mx-auto grid-cols-2 flex">
                  <img src={value.node.thumbnail.url} className="h-20 mr-8" />
                  <div>
                    <div className="text-2xl  flex">
                      {value.node.name}

                      <svg
                        className="mx-5 hidden group-hover:block"
                        width="13"
                        viewBox="0 0 13 14"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <g stroke="#4B587C" stroke-width="1.5" fill="none">
                          <path d="M9.6 4H4.2a2.4 2.4 0 00-2.4 2.4V10"></path>
                          <path d="M6.6 7l3-3-3-3m5.4 9v3H0"></path>
                        </g>
                      </svg>
                    </div>
                    <div className="text-slate-500 pt-3 text-sm">
                      {value.node.description}
                    </div>
                    <div className="pt-3 flex">
                      <svg
                        viewBox="0 0 13 13"
                        xmlns="http://www.w3.org/2000/svg"
                        color="light-gray"
                        style={{
                          width: "12px",
                          height: "18px",
                          marginRight: " 8px",
                        }}
                      >
                        <path
                          d="M6.5.75c-3.31 0-6 2.362-6 5.267 0 2.905 2.69 5.266 6 5.266a6.8 6.8 0 001.036-.08l2.725 1.486a.5.5 0 00.74-.44V9.46a4.893 4.893 0 001.5-3.443C12.5 3.112 9.81.75 6.5.75z"
                          fill="currentColor"
                        ></path>
                      </svg>
                      <div className="text-sm">{value.node.commentsCount}</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
